language: php

php:
  - 7.0

install:
  - composer install --dev --no-interaction
  - composer require "satooshi/php-coveralls:~1.0" --no-progress

before_script:
  - mkdir -p build/coverage

script:
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v