language: php

php:
  - 7.0
  - 7.1

env:
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=3.1.*

before_install:
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - composer update

install:
  - composer install --dev --no-interaction
  - composer require "satooshi/php-coveralls:~1.0"

before_script:
  - mkdir -p build/coverage

script:
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v